### ISSUE TITLE
Error: Could not find 'multi_json' (>= 1.0.0)

### ISSUE THREAD

**Issue by JCount** [Homebrew/homebrew-formula-analytics#2]
`brew formula-analytics` fails with:
`Error: Could not find 'multi_json' (>= 1.0.0) among 28 total gem(s)`.

The beginning of the backtrace is:
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:in `to_spec'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-formula-analytics/vendor/ruby/ruby/2.0.0/gems/signet-0.7.3/lib/compat/multi_json.rb:1:in `<top (required)>'
```
My config and more complete logs: https://gist.github.com/JCount/d5401f873b3a7678bd2fa0a75ce2875b

I tried removing the initial failed attempt, and retrying while forcing the use of Homebrew's vendored ruby, but it exhibited identical behavior. The multi_json gem seems to be installed, and the last file referenced does exist. However, I have no real idea _why_ it is failing.

**Comment by MikeMcQuaid** [comment]
Probably just want to `gem uninstall --force multi_json` and try again. Another option is `gem install --user google-api-client`
