### ISSUE TITLE
Error: cannot load such file -- google/apis/analyticsreporting_v4

### ISSUE THREAD

**Issue by alyssais** [Homebrew/homebrew-formula-analytics#4]
After setting up my config file, I ran `brew formula-analytics`, and on the first run, it installed a bunch of gems, then gave me this error. On subsequent runs, it immediately gives the error.

<details>
<blockquote><pre><samp>
Error: cannot load such file -- google/apis/analyticsreporting_v4
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-formula-analytics/cmd/brew-formula-analytics.rb:33:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:24:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:96:in `<main>'
</samp></pre></blockquote>
</details>

**Comment by MikeMcQuaid** [comment]
What's your default `ruby` point to? Any `GEM_` env set? I'm open to making code changes to fix these problems as it Just Works on my end.
