### ISSUE TITLE
Providing anonymous, read-only access to Homebrew Google Analytics data

### ISSUE THREAD

**Issue by steren** [Homebrew/homebrew-formula-analytics#6]
Hi,
I am a product manager at Google, working on [Bazel](https://github.com/bazelbuild/bazel).
Bazel is distributed on macOS via Homebrew. My goal is to have visibility in the number of installs via this distribution channel.

I can get the https://bintray.com/homebrew/bottles/bazel download stats using the [Bintray REST API](https://bintray.com/docs/api/#_get_daily_downloads), but: this would give me less info that what is captured by Homebrew, this requires to write special code and this requires a Bintray Enterprise account.

Homebrew is instrumented to report data via Google Analytics. But it seems that the Homebrew team did not find a way to share Google Analytics data in read only mode to the public.

Google Analytics events can be exported (in read-only) to Google BigQuery (see [docs](https://support.google.com/analytics/answer/3437618?hl=en)) and BigQuery dataset can be made public (see what is done for the [GitHub Archive](https://www.githubarchive.org/) project).

Stored data has a [free tier of 10GB per month](https://cloud.google.com/bigquery/pricing). I would not think that Homebrew data is more than this.
Querying data from any BigQuery dataset is billed to the project that does the query. So users would, if they go beyond the free quota, pay for queries themselves.

This would allow anybody from the community to get access to raw google analytics event. Increasing Homebrew's transparency.
And this would allow projects to get detailed download numbers (For Bazel: number of downloads per version per day)

Would this be something that the Homebrew team would be interested in?

The only thing that is needed on the Homebrew side is to enable the BigQuery export to a public dataset. This apparently requires Google Analytics 360. Are you already using a Google Analytics 360 account?

What do you think?

**Comment by MikeMcQuaid** [comment]
@steren If this is something Google is able to help us implement then I'm definitely willing to have this exported to BigQuery. It would need to involve no expenditure at any point now or in the future on Homebrew's side.

> Find out more about BigQuery. This integration is currently only available for Google Analytics Premium Properties. Find out more about Google Analytics Premium.

That's the message we see currently so we'd need a lifetime free upgrade from Google to proceed any further.

Is it possible to exclude certain data? I'd want to export almost everything but not allow people to query e.g. individual user activity by their UUID. This would require extracting their UUID from their system and it not being regenerated but I'd rather be safe than sorry; aggregate user data should be sufficient for anyone's (including Homebrew's) use-case.

**Comment by steren** [comment]
As far as I know, there is no way to exclude certain data when performing the export. The way to achieve this would be to keep the exported dataset private, and then to have your own processing pipeline that would populate an aggregated table.

I will see if something is possible regarding Google Analytics Premium.

**Comment by MikeMcQuaid** [comment]
> The way to achieve this would be to keep the exported dataset private, and then to have your own processing pipeline that would populate an aggregated table.

Is this something that either Google Analytics or Google BigQuery can handle?

**Comment by steren** [comment]
> Is this something that either Google Analytics or Google BigQuery can handle?

Not directly. You can read Step 2 of [this blog post](https://cloud.google.com/blog/big-data/2017/04/how-to-build-a-bi-dashboard-using-google-data-studio-and-bigquery) to learn how to achieve this using App Engine. It basically requires to run daily a query that outputs the data you want to put in the aggregate table.

**Comment by MikeMcQuaid** [comment]
Would Google also donate the necessary resources to be able to do that and would you be willing to help with the implementation?

**Comment by steren** [comment]
Regarding implementation: the blog post already gives you a code sample to use.
Regarding resources: App Engine has a free tier. If your app only runs once a day, my guess is that it would be sufficient.

**Comment by MikeMcQuaid** [comment]
> Regarding implementation: the blog post already gives you a code sample to use.

@steren Sure but I think we both know the difference between a blog post sample and an application that's deployed to production is a little different. If you're unable to help there that's fine, it'll just take a bit longer. 

> Regarding resources: App Engine has a free tier. If your app only runs once a day, my guess is that it would be sufficient.

If it is or no longer remains sufficient would Google be able to help with that? I'm not familiar with the way billing works and Homebrew does not have the funds to be able to support this if we have to pay in future.

**Comment by steren** [comment]
I checked internally, we would be happy to enable Premium for your Analytics account.
Could you send to steren@google.com your Google Analytics account ID?

Regarding resources, as I said, I am convinced that the data processing will fit in the App Engine free tier.

**Comment by MikeMcQuaid** [comment]
> I checked internally, we would be happy to enable Premium for your Analytics account.
> Could you send to steren@google.com your Google Analytics account ID?

Great, thanks @steren. Sent.

> Regarding resources, as I said, I am convinced that the data processing will fit in the App Engine free tier.

Ok, good to know, thanks.

**Comment by MikeMcQuaid** [comment]
Google was unable to figure out a way of doing this that didn't involve Homebrew being charged money multiple times so this project is not happening.

**Comment by MikeMcQuaid** [comment]
@steren This information is now publicly available: https://formulae.brew.sh/formula/bazel

You can access this programmatically using the JSON API: https://formulae.brew.sh/docs/api/

It’s on GitHub Pages so don’t worry about taxing our (Homebrew’s) resources accessing the API. Additionally, the data will only change once per day.

Let me know if this is useful to you (or not).

Thanks!
